services:
  alas:
    image: ${ALAS_TEST_IMAGE:-ghcr.io/neanc/alas-pixi-alpine:latest}
    container_name: alas-test

    environment:
      - ALAS_DIR=/alas
      - DEPLOY_TEMPLATE=config/deploy.template-linux.yaml

    volumes:
      - ${ALAS_REPO_PATH:-./AzurLaneAutoScript}:/alas

    ports:
      - "22267:22267"
